### ISSUE TITLE
E/launcher - session not created: Chrome version must be >= 69.0.3497.0

### ISSUE THREAD

**Issue by jamiejackson** [epiclabs-io/docker-cucumber-protractor-chrome#7]
I'm following up with #5, but I'm getting: `E/launcher - session not created: Chrome version must be >= 69.0.3497.0`:
```
$ docker run epiclabs/e2e-test-runner
webdriver-manager: using local installed version 12.0.6
[15:11:44] I/update - geckodriver: unzipping geckodriver-v0.23.0.tar.gz
[15:11:45] I/update - geckodriver: setting permissions to 0755 for /src/node_modules/webdriver-manager/selenium/geckodriver-v0.23.0
[15:11:47] I/update - chromedriver: unzipping chromedriver_2.44.zip
[15:11:48] I/update - chromedriver: setting permissions to 0755 for /src/node_modules/webdriver-manager/selenium/chromedriver_2.44
Waiting for selenium on 127.0.0.1
webdriver-manager: using local installed version 12.0.6
[15:11:50] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/src/node_modules/webdriver-manager/selenium/chromedriver_2.44 -Dwebdriver.gecko.driver=/src/node_modules/webdriver-manager/selenium/geckodriver-v0.23.0 -jar /src/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar -port 4444
[15:11:50] I/start - seleniumProcess.pid: 28
(node:58) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:11:53] I/launcher - Running 1 instances of WebDriver
[15:11:53] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[15:12:54] E/launcher - session not created: Chrome version must be >= 69.0.3497.0
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.9.93-linuxkit-aufs x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.09 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '6ca0024f22cf', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.93-linuxkit-aufs', java.version: '1.8.0_111'
Driver info: driver.version: unknown
[15:12:54] E/launcher - SessionNotCreatedError: session not created: Chrome version must be >= 69.0.3497.0
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.9.93-linuxkit-aufs x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.09 seconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '6ca0024f22cf', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.93-linuxkit-aufs', java.version: '1.8.0_111'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/src/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/src/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/src/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/src/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/src/node_modules/selenium-webdriver/chrome.js:709:29)
    at createDriver (/src/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/src/node_modules/selenium-webdriver/index.js:623:16)
    at Hosted.getNewDriver (/src/node_modules/protractor/lib/driverProviders/driverProvider.ts:60:29)
    at Runner.createBrowser (/src/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/src/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/src/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/src/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/src/node_modules/q/q.js:796:13)
[15:12:54] E/launcher - Process exited with error code 199
webdriver-manager: using local installed version 12.0.6
[15:12:54] I/shutdown - Attempting to shut down selenium nicely
```

**Comment by aescarcha** [comment]
I don't maintain this repository anymore, please contact somebody from [epic labs](https://github.com/epiclabs-io)

**Comment by GitHubUser545** [comment]
I'm facing the same issue.can somebody pls help?.

[12:11:01] E/launcher - session not created: Chrome version must be >= 69.0.3497.0
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 6.1.7601 SP1 x86_64)
[12:11:01] E/launcher - SessionNotCreatedError: session not created: Chrome version must be >= 69.0.3497.0

**Comment by jamiejackson** [comment]
> I don't maintain this repository anymore, please contact somebody from epic labs

Isn't this the epic labs GitHub organization? Maybe @jeoliva has an idea how/where to ask a question, if not here?
